// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6TGG5Ly8fb1YrnDp2l1inSgPod63nLJk',
    appId: '1:999836354325:web:7eba3ff7566dd5985acb1c',
    messagingSenderId: '999836354325',
    projectId: 'shop-manager-123',
    authDomain: 'shop-manager-123.firebaseapp.com',
    storageBucket: 'shop-manager-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLhq1I8TdKcbnMTRuItdmd71KIr6tzq5w',
    appId: '1:999836354325:android:3ef3e825500df88f5acb1c',
    messagingSenderId: '999836354325',
    projectId: 'shop-manager-123',
    storageBucket: 'shop-manager-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGwZ0FzfHXtBYPkDOEBt2jnT_aXFj_sd4',
    appId: '1:999836354325:ios:799d4c2a85770cb85acb1c',
    messagingSenderId: '999836354325',
    projectId: 'shop-manager-123',
    storageBucket: 'shop-manager-123.firebasestorage.app',
    iosBundleId: 'com.shopmanager.shopManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGwZ0FzfHXtBYPkDOEBt2jnT_aXFj_sd4',
    appId: '1:999836354325:ios:799d4c2a85770cb85acb1c',
    messagingSenderId: '999836354325',
    projectId: 'shop-manager-123',
    storageBucket: 'shop-manager-123.firebasestorage.app',
    iosBundleId: 'com.shopmanager.shopManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6TGG5Ly8fb1YrnDp2l1inSgPod63nLJk',
    appId: '1:999836354325:web:e7d349b0c37c93e25acb1c',
    messagingSenderId: '999836354325',
    projectId: 'shop-manager-123',
    authDomain: 'shop-manager-123.firebaseapp.com',
    storageBucket: 'shop-manager-123.firebasestorage.app',
  );
}
